onnx_file:     "yolov8l.onnx"
engine_file:   ""
labels_file:   "yolov8l.yaml"
BATCH_SIZE:    1
INPUT_CHANNEL: 3
image_order:   "BCHW"
channel_order: "BGR"
obj_threshold: 0.4
nms_threshold: 0.45
agnostic:      False
strides:       [8, 16, 32]
num_anchors:   [ 0, 0, 0 ]
img_mean:      [ 0, 0, 0 ]
img_std:       [ 1, 1, 1 ]
alpha:         255.0
keep_ratio:        "true"
normalized: "true"
