onnx_file: "plate_detection.onnx"
labels_file: "plate_detection.yaml"
input_names: "input0"
output_names: ["output0"]
sub_vals: [0, 0, 0]
div_vals: [1.0,1.0, 1.0]
normalized: True
swapBR: True
image_order:   "BCHW"
channel_order: "BGR"
obj_threshold: 0.4
nms_threshold: 0.45
seg_threshold: 0.5
agnostic:      False
num_detect: 20
alpha:   255.0
resize: "keep_ratio"
