onnx_file:     "retinaface2.onnx"
obj_threshold: 0.5
nms_threshold: 0.45
img_mean:      [ 0, 0, 0 ]
img_std:       [ 1, 1, 1 ]    
detect_mask:   False
mask_thresh:   0.5
landmark_std:  1
feature_steps: [32, 16, 8]
anchor_sizes:  [[512, 256], [128, 64], [32, 16]]
alpha:         1.0
resize:        "keep_ratio"
