onnx_file:     "yolov8x-pose.onnx"
engine_file:   ""
labels_file:   "yolov8x-pose.yaml"
BATCH_SIZE:    1
obj_threshold: 0.4
nms_threshold: 0.45
agnostic:      False
strides:       [8, 16, 32]
num_anchors:   [ 0, 0, 0 ]
img_mean:      [ 0, 0, 0 ]
img_std:       [ 1, 1, 1 ]
alpha:         255.0
keep_ratio:        "true"
normalized: "true"
